# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PELT <- function(data, penalty = 0) {
    .Call(`_dust_PELT`, data, penalty)
}

colPow <- function(inputCol, power) {
    .Call(`_dust_colPow`, inputCol, power)
}

test <- function(t, i, j, valuesCumsum, costRecord) {
    .Call(`_dust_test`, t, i, j, valuesCumsum, costRecord)
}

test1D <- function(t, i, j, valuesCumsum, costRecord, optimalCost) {
    .Call(`_dust_test1D`, t, i, j, valuesCumsum, costRecord, optimalCost)
}

test1DRand <- function(t, i, j, valuesCumsum, costRecord, optimalCost) {
    .Call(`_dust_test1DRand`, t, i, j, valuesCumsum, costRecord, optimalCost)
}

testMV1C <- function(t, i, j, valuesCumsum, costRecord, optimalCost) {
    .Call(`_dust_testMV1C`, t, i, j, valuesCumsum, costRecord, optimalCost)
}

modelCost <- function(t, i, valuesCumsum) {
    .Call(`_dust_modelCost`, t, i, valuesCumsum)
}

modelCostMV <- function(t, i, valuesCumsum) {
    .Call(`_dust_modelCostMV`, t, i, valuesCumsum)
}

madEstimator <- function(data) {
    .Call(`_dust_madEstimator`, data)
}

dust_gauss <- function(j, k) {
    .Call(`_dust_dust_gauss`, j, k)
}

dust <- function(data, penalty = 0) {
    .Call(`_dust_dust`, data, penalty)
}

dust1D <- function(data, penalty = 0) {
    .Call(`_dust_dust1D`, data, penalty)
}

dust1DRand <- function(data, penalty = 0, alpha = 1e-9) {
    .Call(`_dust_dust1DRand`, data, penalty, alpha)
}

dust1DRandConstraint <- function(data, penalty = 0, alpha = 1e-9) {
    .Call(`_dust_dust1DRandConstraint`, data, penalty, alpha)
}

dustMV1C <- function(data, penalty = 0) {
    .Call(`_dust_dustMV1C`, data, penalty)
}

