# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title MyModule: Exposing DUST_1D to R
#'
#' @name DUST_1D
#'
#' @description
#' This module exposes the \code{DUST_1D} C++ class to R, allowing you to create
#' instances of \code{DUST_1D} and call its methods directly from R.
#'
#' @export
NULL

#' @title MyModule: Exposing DUST_1D to R
#'
#' @name DUST_1D
#'
#' @description
#' This module exposes the \code{DUST_1D} C++ class to R, allowing you to create
#' instances of \code{DUST_1D} and call its methods directly from R.
#'
#' @export
NULL

#' Calculate Standard Deviation or MAD of Differences in a Numeric Vector
#'
#' The `sdDiff` function calculates a measure of variability (standard deviation or MAD)
#' of a numeric vector.
#' It supports three methods: "HALL", "MAD", and "SD".
#'
#' @param y A numeric vector.
#' @param method A character string specifying the method to use.
#'   Options are: \code{"HALL"}, \code{"MAD"}, and \code{"SD"}.
#'   Default is \code{"HALL"}.
#'
#' @return A numeric value representing the calculated measure of variability
#'   according to the specified method.
#'   \itemize{
#'     \item \code{"HALL"}: Calculates the standard deviation using a specific weighted
#'           difference method (HALL method).
#'     \item \code{"MAD"}: Returns the MAD (Median Absolute Deviation) of the differences
#'           between consecutive elements.
#'     \item \code{"SD"}: Returns the standard deviation of the differences
#'           between consecutive elements.
#'   }
#'
#' @examples
#' y <- c(rnorm(500, mean = 1), rnorm(500,mean = 2))
#' sdDiff(y, "HALL")
#' sdDiff(y, "MAD")
#' sdDiff(y, "SD")
#'
#' @export
sdDiff <- function(y, method = "HALL") {
    .Call(`_dust_sdDiff`, y, method)
}

