# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dust_gauss <- function() {
    .Call(`_dust_dust_gauss`)
}

dust <- function(data, penalty = 0) {
    .Call(`_dust_dust`, data, penalty)
}

